nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Change this to your Next.js app's URL in production
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']  # Change this to your Next.js app's URL in production
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
