security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%env(APP_ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            http_basic: ~
            stateless: true 
