controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# redirecting the homepage
homepage:
    path: /home
    controller: App\Controller\HomeController::index